# Generated by Django 4.2.8 on 2023-12-04 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("modified_at", models.DateTimeField(default=datetime.datetime.now)),
                ("is_active", models.BooleanField(default=0)),
            ],
        ),
    ]
